# Generated by Django 4.2.9 on 2024-01-22 14:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name="author",
            unique_together={("name", "birth_date")},
        ),
    ]
