# Generated by Django 4.2.9 on 2024-01-23 10:36

import api.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_alter_author_name_alter_author_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="birth_date",
            field=models.DateField(validators=[api.models.validate_birth_date]),
        ),
        migrations.AlterField(
            model_name="book",
            name="publish_year",
            field=models.PositiveIntegerField(
                validators=[api.models.validate_publish_year]
            ),
        ),
        migrations.AlterField(
            model_name="storing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="api.book",
            ),
        ),
    ]
