# Generated by Django 4.2.9 on 2024-01-24 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_alter_author_birth_date_alter_book_publish_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="barcode",
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="storing",
            name="book",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="store_history",
                to="api.book",
            ),
        ),
        migrations.AlterField(
            model_name="storing",
            name="quantity",
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name="BooksLeftOver",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "book",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="books",
                        to="api.book",
                    ),
                ),
            ],
        ),
    ]
